### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by zeng32** [zhechen/PLARD#4]
Hi,
Now, I can replicate the result of the test using GPUs.
However, when I train the model with the following command:
python train.py --arch plard --dataset kitti_road --no-visdom --pretrained ./plard_kitti_road.pth
I get the error:
<details>
<summary>below is the error info:</summary>
Found 289 train images

Params: l_rate 0.000050, l_rate_decay: 0.10, l_rate_step: 1, batch_size: 4, mom: 0.99, wd: 0.000500

Using custom loss

/home/u4067/anaconda3/envs/py_plard/lib/python3.7/site-packages/torch/nn/functional.py:2416: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.

  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
/home/u4067/anaconda3/envs/py_plard/lib/python3.7/site-packages/torch/nn/_reduction.py:13: UserWarning: reduction='elementwise_mean' is deprecated, please use reduction='mean' instead.
  warnings.warn("reduction='elementwise_mean' is deprecated, please use reduction='mean' instead.")
Traceback (most recent call last):
  File "train.py", line 185, in <module>
    train(args, logger)
  File "train.py", line 101, in train
    loss = model([images, lidars, labels])
  File "/home/u4067/anaconda3/envs/py_plard/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/u4067/anaconda3/envs/py_plard/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/u4067/anaconda3/envs/py_plard/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/u4067/anaconda3/envs/py_plard/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/u4067/anaconda3/envs/py_plard/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/u4067/anaconda3/envs/py_plard/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/u4067/anaconda3/envs/py_plard/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/u4067/Documents/PLARD/PLARD_intact/ptsemseg/models/plard.py", line 358, in forward
    loss.backward()
  File "/home/u4067/anaconda3/envs/py_plard/lib/python3.7/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/u4067/anaconda3/envs/py_plard/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 120.00 MiB (GPU 0; 7.79 GiB total capacity; 6.37 GiB already allocated; 116.00 MiB free; 6.53 GiB reserved in total by PyTorch)
</details>

Could you please help with this error?
My env:
ubuntu: 16.4
python: 3.7.0
pytorch: 1.4.0
torchfile: 0.1.0
torchversion: 0.2.0
GPU: Geforce RTX 2070
cuda: 10.0

**Comment by zhanjiawang** [comment]
i am same with you,did you solve the problem

**Comment by zeng32** [comment]
It would help if you adopt GPUs with larger memory.
